version: '3.8'

services:
  backend:
    build: .
    container_name: includia-api
    ports:
      - "8080:8080"
    depends_on:
      - oracle
      - rabbitmq
      - redis
    environment:
      - SPRING_DATASOURCE_URL=jdbc:oracle:thin:@oracle:1521/xe
      - SPRING_DATASOURCE_USERNAME=system
      - SPRING_DATASOURCE_PASSWORD=oracle
      - SPRING_RABBITMQ_HOST=rabbitmq
      - SPRING_REDIS_HOST=redis
    networks:
      - includia-net

  oracle:
    image: gvenzl/oracle-xe:21-slim
    container_name: includia-oracle
    ports:
      - "1521:1521"
    environment:
      - ORACLE_PASSWORD=oracle
      - APP_USER=includia
      - APP_USER_PASSWORD=includia
    volumes:
      - oracle_data:/opt/oracle/oradata
    networks:
      - includia-net

  rabbitmq:
    image: rabbitmq:3-management
    container_name: includia-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    environment:
      - RABBITMQ_DEFAULT_USER=guest
      - RABBITMQ_DEFAULT_PASS=guest
    networks:
      - includia-net

  redis:
    image: redis:alpine
    container_name: includia-redis
    ports:
      - "6379:6379"
    networks:
      - includia-net

networks:
  includia-net:
    driver: bridge

volumes:
  oracle_data: