version: '3.8'

services:

  rabbitmq:
    image: rabbitmq:3-management
    container_name: includia-rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    networks:
      - includia-net

  redis:
    image: redis:alpine
    container_name: includia-redis
    ports:
      - "6379:6379"
    networks:
      - includia-net

networks:
  includia-net:
    driver: bridge