spring:
  application:
    name: IncludIA-Java

  cache:
    type: redis

  data:
    redis:
      host: ${REDIS_HOST}
      port: 6379

  datasource:
    url: ${SPRING_DATASOURCE_URL}
    username: ${SPRING_DATASOURCE_USERNAME}
    password: ${SPRING_DATASOURCE_PASSWORD}
    driver-class-name: oracle.jdbc.OracleDriver

  jpa:
    database-platform: org.hibernate.dialect.OracleDialect
    hibernate:
      ddl-auto: update
    show-sql: true

  rabbitmq:
    host: ${SPRING_RABBITMQ_HOST}
    port: 5672
    username: ${SPRING_RABBITMQ_USERNAME}
    password: ${SPRING_RABBITMQ_PASSWORD}

  messages:
    basename: messages
    encoding: UTF-8

# --- CORREÇÃO AQUI: 'api' deve estar na margem esquerda (nível raiz) ---
api:
  iot:
    url: https://app-includia-iot-2771.azurewebsites.net

# 'mq' e 'jwt' também devem estar na margem esquerda
mq:
  queue:
    match: "match-queue"

jwt:
  secret: ${JWT_SECRET}
  expiration:
    hours: 24
